Implementation
PeterSinelnikov/IslandSimulator pull request #1
Opened 2023-01-17 17:10 UTC by PeterSinelnikov

2023-01-18 19:39 UTC, msch4ever requested changes
Код выглядит и читсется хорошо. Есть прара вопросов к неймингу, но читать код было приятно, молодец.
Многопоточность у тебя очень косвенно реализована. Есть недочеты по параллельному доступу к листам. Если бы каждыое животное было отдельным потоком, ты бы столкнулся с проблемами:)

В целом я считаю это зачетом на отлично. Мне очень понравилось. Молодец

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private int birthDay;
:):):)

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private final AnimalType type;
в целом иметь такую обратную зависимость на наследников не совсем правильно. В данном конкретном случае я бы не сказал, что это супер ошибка

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private int maxAmountPerCell;
это по факту част конфигурации, а не параметр данного конкретного животного
Либо сделай статическим полем, либо вынеси в отдельный класс параметров под каждый тип животного

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private double requiredAmountOfFood;
так же скорее глобальный параметр для всех животных конкретного типа. Чтоб использовать наследование на максимум, можешь сделать здесь в энимале абстракный метод get(requiredAmountOfFood) а в наследниках переопредели.
Если у тебя есть логика в абстрактном родительском классе, завязанная на данное поле, просто используй этот геттер, оно сработает

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private double maxDailyWeightLoss;
тоже самое

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +        List<Cell> availableCellsToGo = getAvailableCellsToGo();
хорошо

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +            currentCell.getAnimals().remove(this);
лучше обернуть в синхронный код

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +        this.cell = chooseWhereToGo(availableCellsToGo);
это присваивание лучше перенести внутрь ифа, а возвращенную клетку записат ьв локальную переменную для сравнения и дальнейшего присваивания

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +        List<Cell> availableCellsToGo = getAvailableCellsToGo();
лучше сразу из этого листа исключить текущую клетку прямо в методе getAvailableCellsToGo чтоб потом не делать лишних проверок

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    public boolean isFemale() {
лучше просто изначально назвать переменную из фимейл и не делать этого метода:)

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +            Factory.getInstance().createAnimal(this.type,this.cell);
пробельчик после запятых

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +            animalsReadyToReproduce.get(0).hasOffspring = true;
т.е. берешь первого попавшегося в качестве второго родителя?
если так, то лучше animalsReadyToReproduce.stream().findAny().get();

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private List<Cell> getAvailableCellsToGo() {
нуууууу я понял как оно работает. Но ушло на это пара минут.
похожий на твой апроуч можно достичь более понятным образом.
достаешь все клетки по горизонтали в этом же ряду и все по вертикали в том же столбце.
Далее при помощи либо фор лупов либо лист итератора идешь влево от текущей до упора или пока не упрешься в скорость, вправо, вверх и вниз, при этом добавляя текущие клетки в твой список доступных клеток.

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    private List<Cell> getAvailableCellsToGo() {
но опять же, твоя реализация низкоуровневая и работает. Единственное что, ты не сможешь идти наискосок по факту - только далеко в любом из направлений.

Мой подход с выбором клетки для каждого отдельного хода в зависимости от расстояния которое может животное пройти лишен такого недостатка.
Но ты волен оставить как есть

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +        isAlive = false;
а логика удаления из клетки? там у тебя должен вроде труп еще гнить:)

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/AnimalFactory/Factory.java
> +    public Animal createAnimal(AnimalType type, Cell cell) {
тут по факту переборщил. Можно было обойтись без фабрики под каждый тип животного, а реализовать лямбду прямо тут в инаме

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/AnimalFactory/AnimalFactory.java
> +public interface AnimalFactory {
добавь сюда аннотацию @FunctionalInterface
и тебе не нужно будет реализовывать под каждый тип свою фабрику

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/AnimalType.java
> +    public final int index;
у инамов есть поле под капотом что то типа индекса
each enum value knows its position (indexed from zero) which we can get by calling ordinal() method on it

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +                .filter(this::hasChancesToKill)
норм, т.е. он не тупо ходит, а все же смотрит чего бы там можно было поесть

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        if (lookForDeadHerbivore().isPresent()) {
плохо. Вынеси этот опшинал в локальную переменную, чтобы дважды не вызывать этот метод

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        if (lookForDeadHerbivore().isPresent()) {
яб логику "сожрать чей-то труп" все такие вынес в разрят хищников-падальщиков. Ну и падальщику пофиг на то хищник сдох или травоядное

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +                    .filter(victimAnimal -> AttackingPropParser.getInstance()
проперти в парсере не нужно хранить, лучше вынести в другой класс, а парсер этот класс бы наполнил

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +                    .max(Comparator.comparingDouble(Animal::getWeight))
берет пожирнее

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +                            () -> setWeight(getWeight() - getMaxAmountPerCell())
здесь наверно не getMaxAmountPerCell, а что то типа "сколько теряет массы за ход без еды"?

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        victimAnimal.setOffenderName(this);
если ты просто хотел это записать в исход хода, то смысл есть. А если хотел записать сюда хищника, который убил эту жертву, то лучше сетать этот филд уже после фактической смерти

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +            double weightLoss = (getRequiredAmountOfFood() - consumedFood) / getRequiredAmountOfFood() * getMaxDailyWeightLoss();
а не сложноватая формула для потери веса, если животное не доело?
я думаю что там долждно быть что то типа этогго:
потеряВеса = нужноВДень - сожрано;

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +            double weightLoss = (getRequiredAmountOfFood() - consumedFood) / getRequiredAmountOfFood() * getMaxDailyWeightLoss();
точно ты хотел чтоб getMaxDailyWeightLoss() был в знаменателе?

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        victimAnimal.setWeight(victimAnimal.getWeight() - consumedFood);
это чтоб его мог кто-то дожрать?:)

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/herbivores/Herbivore.java
> +                .orElseGet(this::getCell);
травоядное не пойдет если везде рядом есть хищники?

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/herbivores/omnivores/Omnivore.java
> +        getCell().getAnimals().stream()
нужно условие, врдуг наелось уже травки

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/animals/herbivores/omnivores/Omnivore.java
> +        getCell().getAnimals().stream()
ну или рандомом решить как сегодня будем питаться. И если не наелся, доесть травкой или попробовать кого-то съесть

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/island/Cell.java
> +    public static final int MAX_AMOUNT_OF_PLANTS = 200;
можно вынести в айленд проперти

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/island/Island.java
> +                .map(Cell::getAnimals)
после этого еще один флетмап чтоб все в один лист схлопнуть, а так выходит чуть странновато

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/AnimalSimulationService.java
> +        if (Island.getAllAnimals().size() < 2) {
странный кондишн. Пока не останется одного списка животных?

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/AnimalSimulationService.java
> +                .forEach(Animal::die);
если травки нет, гусеницы дохнут. норм

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/IslandSimulationService.java
> +    private static void growPlants() {
порядок методов поменяй в соответствии с появлением в стартСимуляция

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/AnimalSimulationService.java
> +public class AnimalSimulationService implements Runnable {
лучше переименовать. AnimalDaySimulation

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/IslandSimulationService.java
> +    private static final ScheduledExecutorService ANIMALS_SERVICE = Executors.newScheduledThreadPool(2);
сервисы не являются потоками в общем и целом. Нужно переименовать

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/IslandSimulationService.java
> +    private static final ScheduledExecutorService PLANTS_SERVICE = Executors.newScheduledThreadPool(2);
а почему два?

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/IslandSimulationService.java
> +        ANIMALS_SERVICE.scheduleAtFixedRate(new AnimalSimulationService()
фактически многопоточности нет, но есть вероятность, что текущий день не закончился, а следуюший начался

2023-01-18 19:39 UTC, msch4ever commented on src/main/java/com/company/services/PlantsGrowthService.java
> +public class PlantsGrowthService implements Runnable {
не сервис

2023-01-18 23:33 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/Animal.java
> +    private final AnimalType type;
А как тогда мне правильно решить задачу по привязке типа животного? Мне очень помогло в коде наличие типа (реализованного через enum), так можно было у каждого животного спросить, кто оно такое, без перебирания instance of и проч.

2023-01-18 23:46 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +                            () -> setWeight(getWeight() - getMaxAmountPerCell())
упс, ошибочка вышла, поправлю

2023-01-18 23:49 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        victimAnimal.setWeight(victimAnimal.getWeight() - consumedFood);
Именно! Один хищник начал, другой присоединился, буйвола на всех хватит, но через 2 хода он протухнет и будет удален с карты, поэтому хватай, пока горячее))

2023-01-19 18:49 UTC, msch4ever requested changes

2023-01-19 18:49 UTC, msch4ever commented on src/main/java/com/company/animals/Animal.java
> +    }
public abstract AnimalType getAnimalType();

2023-01-20 20:57 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/Animal.java
> +    private List<Cell> getAvailableCellsToGo() {
Животное может пойти наискосок, почему нет, у меня облась выбранных клеток - получается ромб, внутри которого все клетки достижимы для конкретного животного. Т.е. он может пойти 2 влево и 1 вверх за один ход без проблем.

2023-01-20 20:59 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/Animal.java
> +        isAlive = false;
Реализована не на уровне животного, а на уровне управления симуляцией в классе AnimalDaySimulation

2023-01-20 22:43 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/carnivores/Carnivore.java
> +        victimAnimal.setOffenderName(this);
да, это для статистики хода, чтобы можно было смотреть, кто кого пытался убить

2023-01-20 23:08 UTC, PeterSinelnikov commented on src/main/java/com/company/animals/herbivores/Herbivore.java
> +                .orElseGet(this::getCell);
Да, тровоядное же себе смерти искать не пойдет

2023-01-26 19:57 UTC, PeterSinelnikov commented on src/main/java/com/company/services/IslandSimulationService.java
> +        ANIMALS_SERVICE.scheduleAtFixedRate(new AnimalSimulationService()
А может ли Еxecutor Service перейти к исполнению задач следующего дня, пока в очереди висят задачи предыдущего дня?

2023-01-26 19:58 UTC, PeterSinelnikov commented on src/main/java/com/company/services/IslandSimulationService.java
> +    private static final ScheduledExecutorService PLANTS_SERVICE = Executors.newScheduledThreadPool(2);
исправил на 1

2023-01-26 20:03 UTC, PeterSinelnikov commented on src/main/java/com/company/services/AnimalSimulationService.java
> +        if (Island.getAllAnimals().size() < 2) {
метод getAllAnimals возвращает именно животных, а не листы

2023-01-26 23:36 UTC, merged